// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Marker$MyProjectName = require("./Marker.bs.js");
var Fetcher$MyProjectName = require("./Fetcher.bs.js");
var Markers$MyProjectName = require("./Markers.bs.js");
var Geography$MyProjectName = require("./Geography.bs.js");
var Geographies$MyProjectName = require("./Geographies.bs.js");
var ComposableMap$MyProjectName = require("./ComposableMap.bs.js");
var ZoomableGroup$MyProjectName = require("./ZoomableGroup.bs.js");

var component = ReasonReact.reducerComponent("BasicMap");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Fetcher$MyProjectName.fetchPost("https://immense-river-25513.herokuapp.com/add-location", "ernestobarros");
              return Fetcher$MyProjectName.fetchGet("https://immense-river-25513.herokuapp.com/locations", (function (locations) {
                            return Curry._1(self[/* send */3], /* SetData */[locations]);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var locations = self[/* state */1][/* locations */0];
              return ReasonReact.element(/* None */0, /* None */0, ComposableMap$MyProjectName.make(/* array */[ReasonReact.element(/* None */0, /* None */0, ZoomableGroup$MyProjectName.make(/* array */[
                                        ReasonReact.element(/* None */0, /* None */0, Geographies$MyProjectName.make("world-50m.json", /* array */[(function (geographies, projection) {
                                                      return $$Array.mapi((function (idx, geography) {
                                                                    return ReasonReact.element(/* Some */[String(idx)], /* None */0, Geography$MyProjectName.make(geography, projection, /* array */[]));
                                                                  }), geographies);
                                                    })])),
                                        ReasonReact.element(/* None */0, /* None */0, Markers$MyProjectName.make(/* array */[$$Array.mapi((function (idx, data) {
                                                          var $$location = data.location;
                                                          return ReasonReact.element(/* Some */[String(idx)], /* None */0, Marker$MyProjectName.make(/* record */[/* coordinates */$$location], /* array */[React.createElement("circle", {
                                                                                cx: "0",
                                                                                cy: "0",
                                                                                fill: "red",
                                                                                r: "2"
                                                                              })]));
                                                        }), locations)]))
                                      ]))]));
            }),
          /* initialState */(function () {
              return /* record */[/* locations : array */[]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* locations */action[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
