// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimpleMaps = require("react-simple-maps");

function make(marker, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.Marker, {
              marker: {
                coordinates: /* array */[
                  marker[/* coordinates */0][1],
                  marker[/* coordinates */0][0]
                ]
              }
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
